### ISSUE TITLE
Plugin checklist

### ISSUE THREAD

**Issue by cookie10codes** [percipioglobal/craft-timeloop#21]
- [ ] Project Config is working
- [ ] GraphQL query is returning data
- [ ] Readme.md is provided
- [ ] Graphics (logo / header) is in place
- [ ] Develop team tested out the plugin
- [ ] Check documentation urls are correct
- [ ] Check author name is set to `Percipio`
